spring:
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    password: operation
    url: jdbc:mysql://127.0.0.1:3306/operation?characterEncoding=utf-8&useSSL=false
    username: operation
  cache:
    redis:
      time-to-live: 30m
  jackson:
    default-property-inclusion: non_null
mybatis:
  configuration:
    auto-mapping-behavior: full
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler #将枚举映射成为数值
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.gzsf.operation.model