spring:
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    password: root
    url: jdbc:mysql://127.0.0.1:3306/operation?characterEncoding=utf-8&useSSL=false
    username: root
  cache:
    redis:
      time-to-live: 30m
  jackson:
    default-property-inclusion: non_null
mybatis:
  configuration:
    auto-mapping-behavior: full
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler #将枚举映射成为数值
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.gzsf.operation.model
server:
  port: 5000
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  rowBoundsWithCount: true
  pageSizeZero: true
logging:
  file: logs/operatetion.log